#!/bin/bash
#
# Setup Databricks secrets for Neo4j MCP Server HTTP Connection
# Reads connection info from MCP_ACCESS.json and creates secrets in Databricks
#
# Usage:
#   1. Ensure MCP_ACCESS.json exists (generated by deploy.sh)
#   2. Run: ./scripts/setup-databricks-secrets.sh [--env <file>] [--profile <name>] [scope-name]
#      Examples:
#        ./scripts/setup-databricks-secrets.sh                           # .env -> neo4j_mcp_server
#        ./scripts/setup-databricks-secrets.sh --env .env.manufacturing  # -> manufacturing_mcp_server
#        ./scripts/setup-databricks-secrets.sh --env .env.finance        # -> finance_mcp_server
#        ./scripts/setup-databricks-secrets.sh --profile azure-rk-knight # use specific Databricks CLI profile
#        ./scripts/setup-databricks-secrets.sh --env .env.mfctv2 --profile azure-rk-knight
#        ./scripts/setup-databricks-secrets.sh my-custom-scope           # custom scope name
#   3. Use secrets in Databricks notebooks or HTTP connections
#
# Connection naming:
#   .env                -> connection: neo4j_mcp_server
#   .env.manufacturing  -> connection: manufacturing_mcp_server
#   .env.finance        -> connection: finance_mcp_server
#
# Prerequisites:
#   - Databricks CLI installed and authenticated (databricks auth login)
#   - jq installed for JSON parsing
#   - MCP_ACCESS.json in project root (generated by deploy.sh)

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=_common.sh
source "$SCRIPT_DIR/_common.sh"

# Parse --env, --profile flags and positional args
env_arg=""
profile_arg=""
positional_args=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --env)
            env_arg="${2:-}"
            shift 2
            ;;
        --profile)
            profile_arg="${2:-}"
            shift 2
            ;;
        *)
            positional_args+=("$1")
            shift
            ;;
    esac
done

# Build Databricks CLI profile args
DB_PROFILE_ARGS=()
if [[ -n "$profile_arg" ]]; then
    DB_PROFILE_ARGS=("--profile" "$profile_arg")
fi
resolve_env_file "${env_arg:-.env}"

# Derive connection name from env file suffix
# .env -> neo4j_mcp_server, .env.manufacturing -> manufacturing_mcp_server
env_basename=$(basename "$ENV_FILE")
env_suffix="${env_basename#.env}"
if [[ -z "$env_suffix" ]]; then
    CONNECTION_NAME="neo4j_mcp_server"
else
    # ".manufacturing" -> "manufacturing"
    env_suffix="${env_suffix#.}"
    CONNECTION_NAME="${env_suffix}_mcp_server"
fi

# Configuration
SCOPE_NAME="${positional_args[0]:-mcp-neo4j-secrets}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

echo ""
echo "=========================================="
echo "  Databricks Secrets Setup for Neo4j MCP"
echo "=========================================="
echo ""

log_info "Using secret scope: $SCOPE_NAME"
log_info "Connection name: $CONNECTION_NAME"
[[ -n "$profile_arg" ]] && log_info "Databricks profile: $profile_arg"

# Check for MCP_ACCESS.json
if [[ ! -f "$MCP_ACCESS_FILE" ]]; then
    log_error "MCP_ACCESS.json not found at: $MCP_ACCESS_FILE"
    echo ""
    echo "This file is generated when you deploy the MCP server."
    echo "Run the deployment first:"
    echo "  ./scripts/deploy.sh"
    echo ""
    exit 1
fi

# Check for jq
if ! command -v jq &> /dev/null; then
    log_error "jq is not installed"
    echo "Install with:"
    echo "  macOS:  brew install jq"
    echo "  Ubuntu: sudo apt-get install jq"
    echo "  Windows: choco install jq"
    exit 1
fi

# Check for Databricks CLI
if ! command -v databricks &> /dev/null; then
    log_error "Databricks CLI not found"
    echo ""
    echo "Install with: pip install databricks-cli"
    echo "Or: brew install databricks"
    echo ""
    echo "Then authenticate with: databricks auth login"
    exit 1
fi

# Verify Databricks authentication
log_step "Verifying Databricks CLI authentication..."
if ! databricks auth describe "${DB_PROFILE_ARGS[@]}" &> /dev/null; then
    log_error "Databricks CLI is not authenticated"
    echo ""
    echo "Run: databricks auth login"
    echo "Or configure a profile in ~/.databrickscfg"
    exit 1
fi
log_info "Databricks CLI authenticated"

# Load values from MCP_ACCESS.json
log_step "Loading configuration from MCP_ACCESS.json"

MCP_ENDPOINT=$(jq -r '.endpoint // empty' "$MCP_ACCESS_FILE")
MCP_API_KEY=$(jq -r '.api_key // empty' "$MCP_ACCESS_FILE")
MCP_PATH=$(jq -r '.mcp_path // "/mcp"' "$MCP_ACCESS_FILE")

# Validate required values
missing=()
[[ -z "$MCP_ENDPOINT" ]] && missing+=("endpoint")
[[ -z "$MCP_API_KEY" ]] && missing+=("api_key")

if [[ ${#missing[@]} -gt 0 ]]; then
    log_error "Missing required values in MCP_ACCESS.json: ${missing[*]}"
    echo ""
    echo "Ensure MCP_ACCESS.json contains valid endpoint and api_key values."
    echo "Re-run the deployment: ./scripts/deploy.sh"
    exit 1
fi

log_info "Endpoint: $MCP_ENDPOINT"
log_info "MCP Path: $MCP_PATH"
log_info "API Key: [REDACTED - ${#MCP_API_KEY} characters]"

# Construct the full MCP URL (endpoint + path)
MCP_FULL_URL="${MCP_ENDPOINT}${MCP_PATH}"

# Create secret scope (ignore error if already exists)
log_step "Creating secret scope: $SCOPE_NAME"
if databricks secrets create-scope "$SCOPE_NAME" "${DB_PROFILE_ARGS[@]}" 2>/dev/null; then
    log_info "Secret scope created successfully"
else
    log_warn "Secret scope already exists (or failed to create - continuing)"
fi

# Function to set a secret
set_secret() {
    local key=$1
    local value=$2
    log_info "Setting secret: $key"
    # Use echo -n to avoid trailing newline, pipe to put-secret
    echo -n "$value" | databricks secrets put-secret "$SCOPE_NAME" "$key" "${DB_PROFILE_ARGS[@]}"
}

# Set secrets
log_step "Storing secrets in Databricks"

set_secret "endpoint" "$MCP_ENDPOINT"
set_secret "api_key" "$MCP_API_KEY"
set_secret "mcp_path" "$MCP_PATH"
set_secret "mcp_url" "$MCP_FULL_URL"
set_secret "connection_name" "$CONNECTION_NAME"

log_info "All secrets stored successfully"

# Validate secrets were set
log_step "Validating secrets..."
echo ""
echo "Secrets in scope '$SCOPE_NAME':"
databricks secrets list-secrets "$SCOPE_NAME" "${DB_PROFILE_ARGS[@]}"
echo ""

# Print usage instructions
log_info "Setup complete!"
echo ""
echo "=========================================="
echo "  Usage Instructions"
echo "=========================================="
echo ""
echo "1. In a Databricks notebook, retrieve secrets with dbutils:"
echo ""
echo "   SCOPE_NAME = \"$SCOPE_NAME\""
echo "   MCP_ENDPOINT = dbutils.secrets.get(SCOPE_NAME, \"endpoint\")"
echo "   MCP_API_KEY = dbutils.secrets.get(SCOPE_NAME, \"api_key\")"
echo "   MCP_URL = dbutils.secrets.get(SCOPE_NAME, \"mcp_url\")"
echo ""
echo "2. Create an HTTP connection with SQL (requires Unity Catalog):"
echo ""
echo "   CREATE CONNECTION $CONNECTION_NAME TYPE HTTP"
echo "   OPTIONS ("
echo "     host '$MCP_ENDPOINT',"
echo "     port '443',"
echo "     base_path '$MCP_PATH',"
echo "     bearer_token secret ('$SCOPE_NAME', 'api_key')"
echo "   );"
echo ""
echo "3. Use the HTTP connection to call MCP tools:"
echo ""
echo "   SELECT http_request("
echo "     conn => '$CONNECTION_NAME',"
echo "     method => 'POST',"
echo "     path => '/',"
echo "     json => '{\"jsonrpc\":\"2.0\",\"method\":\"tools/call\",\"params\":{\"name\":\"get-schema\",\"arguments\":{}},\"id\":1}'"
echo "   );"
echo ""
echo "=========================================="
echo ""
echo "Note: This integration provides READ-ONLY access to Neo4j."
echo "The MCP server is deployed in read-only mode (write-cypher disabled)."
echo ""
